### PR TITLE
travis auto testing and delete repository command

### PR DESCRIPTION
**Pull request by efthym**
This pull request is related to my comment on issue: education/teachers#3 about using travis for auto testing of students' private repos and on education/teachers#28 about managing a course with limited number of private repos by deleting and re-using repos.
Since I need both these capabilities for a course I am about to run, I went ahead and worked on them.
I have to warn you though that I don't know Ruby, thus the code is of poor style. 
If these features are useful, hopefully someone more proficient on Ruby can modify the code.
Changes:
- In create_repos command, I added a few lines which enable the repository on Travis
- In push_files, I added code that looks for a Travis badge in a README.md file and replaces the repo name in the URL, so that it matches the student's repo name.
- Added a delete_repos command (and action) to delete all repos of a piece of coursework.

### CODE REVIEW

**Comment by tarebyte** [comment]
@efthym this is a lot for one pull request. Any chance you could split this up into 3? One for each of the new features?

I'd be more than happy to help you out with looking over the code.

**Comment by efthym** [comment]
@tarebyte thanks. How's this best done in github?
Close this pull request and start new ones?

**Comment by tarebyte** [comment]
I took a stab at breaking these up in to two branches and made it a step by step process. If you're new to Git I would also take a look at [The GitHub Flow](https://guides.github.com/introduction/flow/index.html). GitHub has a nice workflow for introducing pull requests.

My idea is to break this up in to two branches `travis-auto-testing` and `delete-repos`

I apologize for the verbosity, but I took a quick shot at splitting up the features, and this is how it came out.

```bash
# Starting from your master branch

# Travis Pull Request
git checkout -b travis-auto-testing
git reset --soft HEAD~5
git reset lib/teachers_pet/{actions,commands}/delete_repos.rb
git clean -f
git commit -m "removed deleted_repos from branch"

git push [your remote here] travis-pull-request

git checkout master

# Delete Repos Pull Request
git checkout -b delete-repos
git reset --hard HEAD~2
git reset --soft HEAD~3
git reset Gemfile lib/teachers_pet/actions/{create_repos.rb,push_files.rb}
git checkout Gemfile lib/teachers_pet/actions/{create_repos.rb,push_files.rb}
git commit -m "removed travis from history"

git push [your remote here] delete-repos
```

**Comment by efthym** [comment]
Thanks a lot for showing the commands which split the features into separate branches.

**Pull request closed without merging**
